name: Validate Metrics

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  validate-metrics:
    name: Validate metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Validate Metrics (v0.1.0)
        uses: azure/online-experimentation-deploy-metrics@v2-beta
        with:
          path: |
            custom/metrics-*.json  
            genai/metrics-*-v0.1.0.json
          online-experimentation-workspace-endpoint: ${{ vars.ONLINE_EXPERIMENTATION_WORKSPACE_ID }}
          operation: validate